/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:4cf8cafb-1595-4fb1-bbdd-0f369f45e6f9",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_pO0ioZihh",
    "aws_user_pools_web_client_id": "3e5os08ockbvg4695kf4nj2vul",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://k3qc5ic3bfh7tp66k7bakv467u.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-2iy6v4z3sbdovjajccg3sk3szu",
    "aws_user_files_s3_bucket": "amplifyapp0559ba5fc3444c399371c0d61a21559d112425-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
